Models/Wedding.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

namespace planner.Models
{
    public class Wedding : BaseEntity
    {
        public int WeddingId {get;set;}
        public string Wedder1 { get; set; }
        public string Wedder2 {get;set;}
        public DateTime Date { get; set; }
        public string Address { get; set; }
        public int UserId { get; set; }
        public User User { get; set; }
        public List<Rsvp> Guests { get; set; }

        public Wedding(){
            Guests = new List<Rsvp>();
        }
    }
}

Controllers/PlannerController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using planner.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;

namespace planner.Controllers
{
    public class PlannerController : Controller
    {

        private PlannerContext _context;
 
        public PlannerController(PlannerContext context)
        {
            _context = context;
        }
 
        [HttpGet]
        [Route("/dashboard")]
        public IActionResult Index()
        {
            ViewBag.AllWeddings = _context.Weddings.Include(wed => wed.Guests).ToList();
            if(HttpContext.Session.GetInt32("id") == null){
                return Redirect("/");
            }
            ViewBag.Id = HttpContext.Session.GetInt32("id");
            ViewBag.Temp = _context.Users.Include(a => a.Rsvps);
            return View();
            // Other code
        }

        [HttpPost]
        [Route("/newwedding")]
        public IActionResult NewWedding(PlanViewModel model)
        {
            if(ModelState.IsValid){
                Wedding NewWed = new Wedding {
                    Wedder1=model.Wedder1,
                    Wedder2=model.Wedder2,
                    Date=model.Date, 
                    Address=model.Address,
                    UserId = (int)HttpContext.Session.GetInt32("id"),
                };
                _context.Add(NewWed);
                _context.SaveChanges();
                return Redirect("/dashboard");
            }
            return View("PlanWedding");
        }

        [HttpGet]
        [Route("/delete/{num}")]
        public IActionResult Delete(int num){
            Wedding thiswedding = _context.Weddings.Include(b => b.Guests).SingleOrDefault(a => a.WeddingId == num);
            foreach(Rsvp guest in thiswedding.Guests){
                _context.Rsvps.Remove(guest);
            }
            _context.Weddings.Remove(thiswedding);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

       [HttpGet]
       [Route("/rsvp/{num}")]
       public IActionResult Rsvp(int num){
          // Wedding thiswedding = _context.Weddings.SingleOrDefault(a => a.WeddingId == num);
           Rsvp newRsvp = new Rsvp {
               UserId = (int)HttpContext.Session.GetInt32("id"),
               WeddingId = num
           };
           _context.Rsvps.Add(newRsvp);
           _context.SaveChanges();
           return RedirectToAction("Index");
       }

       [HttpGet]
       [Route("/unrsvp/{num}")]
       public IActionResult Unrsvp(int num){
           Wedding thiswedding = _context.Weddings.Include(a => a.Guests).SingleOrDefault(a => a.WeddingId == num);
           foreach(Rsvp guest in thiswedding.Guests){
               if(guest.UserId == (int)HttpContext.Session.GetInt32("id")){
                   _context.Rsvps.Remove(guest);
               }
           }
            _context.SaveChanges();
           return RedirectToAction("Index");
       }

       [HttpGet]
       [Route("/weddings/{num}")]
       public IActionResult Wedding(int num){
           ViewBag.Wedding = _context.Weddings.Where(a => a.WeddingId == num).Include(wed => wed.Guests).ThenInclude(a => a.User).ToList();
           return View();
       }

       [HttpGet]
       [Route("/planwedding")]
       public IActionResult PlanWedding(){
           return View();
       }
    }
}

Views/Planner/Index.cshtml
<html>
    <head>
       <meta charset='utf-8'>
       <title>Weddings</title>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <link rel="stylesheet" href="~/css/style.css"/>
    </head>
    <body>
        <h1>Welcome to the Wedding Planner</h1>
        <a href="/logout">Log Out</a> <br>
        <table>
            <tr>
                <th>Wedding &nbsp; &nbsp;</th>
                <th>Date &nbsp; &nbsp;</th>
                <th>Guest &nbsp; &nbsp;</th>
                <th>Action &nbsp; &nbsp; </th>
            </tr>
            @{
                foreach(var wedding in ViewBag.AllWeddings){
                    <tr>
                        <td><a href=/weddings/@wedding.WeddingId>@wedding.Wedder1 & @wedding.Wedder2</a></td>
                        <td>@wedding.Date.ToString("MMM d, yyyy") &nbsp; &nbsp;</td>
                        <td>@wedding.Guests.Count</td>
                        @if(wedding.UserId == ViewBag.Id){
                            <td><a href=/delete/@wedding.WeddingId>Delete</a></td>
                        }
                        else{
                            Boolean isrsvp = false; 
                            foreach(var guest in wedding.Guests){
                                if(guest.UserId == ViewBag.Id){
                                    isrsvp = true;
                                    break;
                                }
                            }
                            if(isrsvp == true){
                                <td><a href=/unrsvp/@wedding.WeddingId>Un-RSVP</a></td>
                            }
                            else{
                                <td><a href=/rsvp/@wedding.WeddingId>RSVP</a></td>
                            }
                        }
                    </tr>
                }    
            }
        </table>
        <form action="/planwedding">
            <button type="submit">Add a new wedding</button>
        </form>

        @{
            foreach(var wed in ViewBag.Temp){
                if(wed.UserId == ViewBag.Id){
                    foreach(var rsvp in wed.Rsvps){
                        <p>RSVP'd for @rsvp.WeddingId</p>
                    }
                }
            }
        }
    </body>
</html>

Views/Planner/PlanWedding.cshtml
@model planner.Models.PlanViewModel
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'>
        <title>Index</title>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <link rel="stylesheet" href="~/css/style.css"/>
    </head>
    <body>
        <div class="wrapper">
            <h1>Write a Review</h1>
            <a href="/logout">Log Out</a>
            <a href="/dashboard">Dashboard</a><br>
            <form asp-controller="Planner" asp-action="NewWedding" method="post">
                <label asp-for="Wedder1">Wedder 1:</label>
                <input asp-for="Wedder1"/><br>
                <label asp-for="Wedder2">Wedder 2:</label>
                <input asp-for="Wedder2"/><br>
                <label asp-for="Date">Date:</label>
                <input asp-for="Date"/><br>
                <label asp-for="Address">Wedding Address:</label>
                <input asp-for="Address"/><br>
                <button type="submit">Create</button>
            </form>
            <br>
            <div asp-validation-summary="All"></div>
        </div>
    </body>
</html>

Views/Planner/Wedding.cshtml
<html>
    <head>
       <meta charset='utf-8'>
       <title>Weddings</title>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <link rel="stylesheet" href="~/css/style.css"/>
    </head>
    <body>
        <h1>@ViewBag.Wedding[0].Wedder1 & @ViewBag.Wedding[0].Wedder2 's wedding</h1>
        <a href="/logout">Log Out</a>
        <a href="/dashboard">Dashboard</a><br>
        <h3>Date: @ViewBag.Wedding[0].Date.ToString("MMMM d, yyyy")</h3>
        <h3>Guests:</h3>
        @{
            foreach(var guest in ViewBag.Wedding[0].Guests){
                <span>@guest.User.FirstName @guest.User.LastName</span> <br>
            }
        }
        <h3>Address: @ViewBag.Wedding[0].Address</h3>
        
    </body>
</html>